version: "3.8"

services:
  mockserver:
    image: mockserver/mockserver
    container_name: mockserver
    ports:
      - "1080:1080"
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/mockserver.json
    volumes:
      - ./mockserver.json:/config/mockserver.json
